# Generated by Django 4.2.1 on 2023-05-19 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('icon', models.CharField(max_length=80)),
                ('bg_color', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('publish_date', models.DateTimeField()),
                ('body', models.CharField(max_length=2500)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notesApp.categorie')),
            ],
        ),
    ]
