# Generated by Django 4.2.1 on 2023-05-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Node',
            new_name='Note',
        ),
    ]
